#!/usr/bin/ruby

require 'rubygems'
require 'twitter'

# a simple TwitPic client

CONFIG = YAML::load(File.read(File.expand_path('~')+'/configs/twitter.yaml'))


if ARGV.length < 1
  puts "Usage: tw <tweet>"
  exit
end

input = nil
if !STDIN.tty?
  input = $stdin.read
end

tweet = "#{ARGV.join(' ')} #{input}".strip 

begin
  httpauth = Twitter::HTTPAuth.new(
    CONFIG[:login][:username], 
    CONFIG[:login][:password] 
  )
  client = Twitter::Base.new(httpauth)
  #client.update(tweet)
  puts "Tweeted: #{tweet}"
rescue SocketError => e
  puts "Oops, #{e.inspect}"
end
